enableConstraintsChecks: true

enableHardenedMode: true

npmRegistryServer: "https://registry.npmmirror.com"

enableInlineHunks: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
